services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    container_name: "db"
    volumes:
      - /mnt/db:/var/lib/postgresql/data



  # api_service:
  #   build: ./api_service
  #   ports:
  #     - "${API_PORT}:8000"

  # parser_service:
  #   build: ./parser_service
  #   volumes:
  #     - ./logs:/app/logs

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    container_name: "nginx"

volumes:
  db:
